Repository authelia/authelia, pull requests merged in 2022-04, with the labels that each got.

#3043 feat(web): add de i18n translation
  web/src/i18n/index.ts
  web/src/i18n/locales/de.json
Labels: Ready

#2988 feat(configuration): allow rfc4918 http verbs in acl
  api/openapi.yml
  docs/configuration/access-control.md
  internal/configuration/validator/access_control.go
  internal/configuration/validator/access_control_test.go
  internal/configuration/validator/const.go
Labels: Ready

#2969 feat(oidc): implement amr claim
  docs/configuration/identity-providers/oidc.md
  internal/handlers/handler_oidc_authorization.go
  internal/handlers/handler_oidc_consent.go
  internal/handlers/handler_sign_duo.go
  internal/handlers/handler_sign_totp.go
  internal/handlers/handler_sign_webauthn.go
  internal/handlers/oidc.go
  internal/handlers/oidc_test.go
  internal/handlers/response.go
  internal/model/oidc.go
  internal/oidc/amr.go
  internal/oidc/amr_test.go
  internal/oidc/client.go
  internal/oidc/client_test.go
  internal/oidc/const.go
  internal/oidc/store.go
  internal/oidc/types.go
  internal/oidc/types_test.go
  internal/session/provider_test.go
  internal/session/types.go
  internal/session/user_session.go
  internal/suites/example/compose/oidc-client/docker-compose.yml
  internal/suites/example/compose/oidc-client/entrypoint.sh
Labels: Ready

#2789 feat(authorization): domain regex match with named groups
  config.template.yml
  docs/configuration/access-control.md
  internal/authorization/access_control_domain.go
  internal/authorization/access_control_resource.go
  internal/authorization/access_control_rule.go
  internal/authorization/access_control_subjects.go
  internal/authorization/authorizer_test.go
  internal/authorization/const.go
  internal/authorization/types.go
  internal/authorization/types_test.go
  internal/authorization/util.go
  internal/authorization/util_test.go
  internal/configuration/config.template.yml
  internal/configuration/decode_hooks.go
  internal/configuration/decode_hooks_test.go
  internal/configuration/provider.go
  internal/configuration/provider_test.go
  internal/configuration/schema/access_control.go
  internal/configuration/test_resources/config_domain_bad_regex.yml
  internal/configuration/test_resources/config_domain_regex.yml
  internal/configuration/validator/access_control.go
  internal/configuration/validator/access_control_test.go
  internal/configuration/validator/const.go
Labels: Ready

#2785 feat(templates): display link in mails sent by authelia
  internal/templates/html_email.go
Labels: Ready

#2828 feat(notification): password reset notification custom templates
  docs/configuration/notifier/index.md
  internal/configuration/schema/notifier.go
  internal/configuration/validator/const.go
  internal/configuration/validator/notifier.go
  internal/handlers/handler_reset_password_step1.go
  internal/handlers/handler_reset_password_step2.go
  internal/middlewares/identity_verification.go
  internal/session/types.go
  internal/suites/example/compose/nginx/portal/docker-compose.yml
  internal/templates/const.go
  internal/templates/html_email_step_1.go
  internal/templates/html_email_step_2.go
  internal/templates/plaintext_email_step_1.go
  internal/templates/plaintext_email_step_2.go
Labels: Ready

#3087 fix(server): respond with 404/405 appropriately
  internal/handlers/response.go
  internal/handlers/types.go
  internal/server/const.go
  internal/server/handler_notfound.go
  internal/server/server.go
  internal/suites/scenario_backend_protection_test.go
Labels: P4, Needs Review

#3065 feat: implement mutual tls in the web server
  cmd/authelia-scripts/cmd_bootstrap.go
  config.template.yml
  docs/configuration/server.md
  docs/security/measures.md
  internal/commands/certificates.go
  internal/commands/root.go
  internal/configuration/config.template.yml
  internal/configuration/schema/server.go
  internal/configuration/validator/const.go
  internal/configuration/validator/server.go
  internal/configuration/validator/server_test.go
  internal/server/const.go
  internal/server/server.go
  internal/server/server_test.go
  internal/suites/environment.go
  internal/suites/suite_cli_test.go
  internal/utils/certificates.go
  internal/utils/certificates_test.go
Labels: Ready

#3005 feat(oidc): provide cors config including options handlers
  config.template.yml
  docs/configuration/identity-providers/oidc.md
  internal/configuration/config.template.yml
  internal/configuration/provider_test.go
  internal/configuration/schema/identity_providers.go
  internal/configuration/test_resources/config_oidc.yml
  internal/configuration/validator/const.go
  internal/configuration/validator/identity_providers.go
  internal/configuration/validator/identity_providers_test.go
  internal/handlers/const.go
  internal/handlers/handler_jwks.go
  internal/handlers/handler_oauth_introspection.go
  internal/handlers/handler_oauth_revocation.go
  internal/handlers/handler_oidc_authorization.go
  internal/handlers/handler_oidc_consent.go
  internal/handlers/handler_oidc_token.go
  internal/handlers/handler_oidc_userinfo.go
  internal/handlers/handler_oidc_wellknown.go
  internal/handlers/oidc_register.go
  internal/middlewares/const.go
  internal/middlewares/cors.go
  internal/middlewares/cors_test.go
  internal/oidc/const.go
  internal/oidc/provider_test.go
  internal/server/const.go
  internal/server/error_handler.go
  internal/server/handler_notfound.go
  internal/server/handlers.go
  internal/server/options_handler.go
  internal/server/server.go
  internal/server/template.go
  internal/utils/strings.go
  internal/utils/strings_test.go
Labels: P1, Needs Review

#3125 refactor(templates): utilize more accurate naming
  docs/configuration/notifier/index.md
  examples/templates/notifications/README.md
  examples/templates/notifications/html_email_with_button_and_link.html
  internal/configuration/validator/notifier.go
  internal/handlers/handler_reset_password_step2.go
  internal/middlewares/identity_verification.go
  internal/templates/const.go
  internal/templates/email_identity_verification_html.go
  internal/templates/email_identity_verification_plaintext.go
  internal/templates/email_password_reset_html.go
  internal/templates/email_password_reset_plaintext.go
  internal/templates/plaintext_email_step_1.go
  internal/templates/plaintext_email_step_2.go
Labels: P3, Ready

#3081 feat(configuration): configurable default second factor method
  config.template.yml
  docs/configuration/miscellaneous.md
  docs/configuration/password_policy.md
  docs/configuration/secrets.md
  docs/configuration/webauthn.md
  internal/configuration/config.template.yml
  internal/configuration/schema/configuration.go
  internal/configuration/schema/keys.go
  internal/configuration/schema/keys_test.go
  internal/configuration/validator/configuration.go
  internal/configuration/validator/configuration_test.go
  internal/configuration/validator/const.go
  internal/configuration/validator/identity_providers.go
  internal/handlers/handler_user_info.go
  internal/model/user_info.go
  internal/model/user_info_test.go
Labels: P2, Needs Review
