Repository authelia/authelia, pull requests merged in 2022-10, with the labels that each got.

#3968 feat(web): i18n local storage detector
  web/src/i18n/detectors/localStorageCustom.ts
  web/src/i18n/index.ts
Labels: priority/4/normal, status/ready

#3793 feat: envoy support
  cmd/authelia-gen/cmd_github.go
  config.template.yml
  internal/configuration/config.template.yml
  internal/handlers/handler_sign_duo_test.go
  internal/handlers/handler_sign_totp_test.go
  internal/handlers/handler_verify.go
  internal/handlers/handler_verify_test.go
  internal/handlers/util.go
  internal/middlewares/authelia_context.go
  internal/middlewares/const.go
  internal/server/handlers.go
  internal/suites/Envoy/configuration.yml
  internal/suites/Envoy/docker-compose.yml
  internal/suites/Envoy/users.yml
  internal/suites/example/compose/envoy/docker-compose.yml
  internal/suites/example/compose/envoy/envoy.yaml
  internal/suites/suite_envoy.go
  internal/suites/suite_envoy_test.go
Labels: priority/4/normal, status/ready

#4061 feat(authentication): permit feature detection failures
  .github/ISSUE_TEMPLATE/bug-report.yml
  cmd/authelia-gen/templates/web_i18n_index.ts.tmpl
  cmd/authelia-scripts/cmd/gen.go
  docs/content/en/blog/pre-release-notes-4.37/index.md
  docs/data/configkeys.json
  internal/authentication/ldap_user_provider_startup.go
  internal/authentication/ldap_user_provider_test.go
  internal/configuration/schema/authentication.go
  internal/configuration/schema/keys.go
Labels: priority/4/normal, status/needs-review

#3989 feat(oidc): jwk certificates
  config.template.yml
  docs/content/en/configuration/identity-providers/open-id-connect.md
  internal/configuration/config.template.yml
  internal/configuration/const.go
  internal/configuration/decode_hooks.go
  internal/configuration/decode_hooks_test.go
  internal/configuration/provider.go
  internal/configuration/provider_test.go
  internal/configuration/schema/const.go
  internal/configuration/schema/identity_providers.go
  internal/configuration/schema/keys.go
  internal/configuration/schema/types.go
  internal/configuration/schema/types_test.go
  internal/configuration/validator/const.go
  internal/configuration/validator/identity_providers.go
  internal/configuration/validator/identity_providers_test.go
  internal/handlers/handler_oidc_userinfo.go
  internal/logging/logger.go
  internal/oidc/keys.go
  internal/oidc/keys_test.go
  internal/oidc/provider.go
  internal/oidc/provider_test.go
  internal/oidc/store_test.go
  internal/oidc/types.go
  internal/utils/crypto.go
Labels: priority/3/medium, status/needs-review, area/openid-connect

#3855 feat(notification): add disable_start_tls option
  docs/content/en/configuration/notifications/smtp.md
  internal/configuration/schema/keys.go
  internal/configuration/schema/notifier.go
  internal/configuration/validator/const.go
  internal/configuration/validator/notifier.go
  internal/notification/smtp_notifier.go
Labels: priority/4/normal, status/ready

#3789 docs: add envoy docs
  README.md
  docs/content/en/integration/kubernetes/istio.md
  docs/content/en/integration/kubernetes/nginx-ingress.md
  docs/content/en/integration/proxies/caddy.md
  docs/content/en/integration/proxies/envoy.md
  docs/content/en/integration/proxies/support.md
  docs/content/en/overview/prologue/supported-proxies.md
Labels: priority/4/normal, status/ready

#3990 feat(authorization): query parameter
  cmd/authelia-gen/cmd_code.go
  docs/content/en/configuration/security/access-control.md
  docs/content/en/integration/openid-connect/synology-dsm/index.md
  docs/content/en/reference/guides/rule-operators.md
  internal/authorization/access_control_query.go
  internal/authorization/access_control_rule.go
  internal/authorization/authorizer.go
  internal/authorization/authorizer_test.go
  internal/authorization/const.go
  internal/authorization/types.go
  internal/commands/crypto_hash.go
  internal/configuration/schema/access_control.go
  internal/configuration/schema/keys.go
  internal/configuration/validator/access_control.go
  internal/configuration/validator/access_control_test.go
  internal/configuration/validator/const.go
Labels: priority/3/medium, status/needs-review

#4026 feat(oidc): hashed client secrets
  cmd/authelia-gen/templates/docs-contributing-development-commitmsg.md.tmpl
  docs/content/en/configuration/identity-providers/open-id-connect.md
  docs/content/en/contributing/guidelines/commit-message.md
  docs/content/en/contributing/guidelines/pull-request.md
  docs/content/en/integration/openid-connect/apache-guacamole/index.md
  docs/content/en/integration/openid-connect/argocd/index.md
  docs/content/en/integration/openid-connect/bookstack/index.md
  docs/content/en/integration/openid-connect/cloudflare-zerotrust/index.md
  docs/content/en/integration/openid-connect/gitea/index.md
  docs/content/en/integration/openid-connect/gitlab/index.md
  docs/content/en/integration/openid-connect/grafana/index.md
  docs/content/en/integration/openid-connect/harbor/index.md
  docs/content/en/integration/openid-connect/hashicorp-vault/index.md
  docs/content/en/integration/openid-connect/komga/index.md
  docs/content/en/integration/openid-connect/nextcloud/index.md
  docs/content/en/integration/openid-connect/outline/index.md
  docs/content/en/integration/openid-connect/portainer/index.md
  docs/content/en/integration/openid-connect/proxmox/index.md
  docs/content/en/integration/openid-connect/seafile/index.md
  docs/content/en/integration/openid-connect/synapse/index.md
  docs/content/en/reference/guides/rule-operators.md
  internal/configuration/decode_hooks.go
  internal/configuration/provider.go
  internal/configuration/schema/identity_providers.go
  internal/configuration/schema/types.go
  internal/configuration/test_resources/config_oidc.yml
  internal/configuration/validator/identity_providers.go
  internal/configuration/validator/identity_providers_test.go
  internal/oidc/client.go
  internal/oidc/client_test.go
  internal/oidc/hasher.go
  internal/oidc/hasher_test.go
  internal/oidc/provider.go
  internal/oidc/provider_test.go
  internal/oidc/store_test.go
  internal/oidc/types.go
Labels: priority/4/normal, status/needs-review, area/openid-connect
