Repository authelia/authelia, pull requests merged in 2022-09, with the labels that each got.

#4014 fix(web): broadcastchannel not supported on old safari
  web/package.json
  web/pnpm-lock.yaml
  web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx
  web/src/views/LoginPortal/LoginPortal.tsx
Labels: status/ready

#4071 build: add container labels and annotations
  cmd/authelia-scripts/cmd/build.go
  cmd/authelia-scripts/cmd/docker.go
  cmd/authelia-scripts/cmd/helpers.go
  cmd/authelia-scripts/cmd/helpers_docker.go
  cmd/authelia-scripts/cmd/types.go
  cmd/authelia-scripts/cmd/xflags.go
  internal/utils/version.go
  internal/utils/version_test.go
Labels: priority/4/normal, status/needs-review

#4037 fix(authorization): regex subj doesn't redirect anon user
  internal/authorization/access_control_domain.go
  internal/authorization/access_control_resource.go
  internal/authorization/access_control_rule.go
  internal/authorization/authorizer.go
  internal/authorization/authorizer_test.go
  internal/authorization/const.go
  internal/authorization/regexp.go
  internal/authorization/util.go
  internal/handlers/handler_verify_test.go
Labels: priority/4/normal, status/ready
